### ISSUE TITLE
Code blocks displayed as inline code

### ISSUE THREAD

**Issue by JannisBush** [babe-project/babe-docs#1]

**Comment by x-ji** [comment]
I'll take a look at it

**Comment by MarauderPixie** [comment]
There seems to be a problem with the `rtd-dropdown` theme; see [this comment](https://github.com/mkdocs/mkdocs/issues/1692#issuecomment-443498806). Should we change it?

**Comment by x-ji** [comment]
This is actually discussed in this issue: https://github.com/cjsheets/mkdocs-rtd-dropdown/issues/12 and fixed in this PR: https://github.com/cjsheets/mkdocs-rtd-dropdown/pull/27/commits/59b4cecd8404f80468afdadd0cdf821ec358ea01

Maybe we can just apply the changes from that PR manually.

**Comment by x-ji** [comment]
Should now be fixed. The `rtd-dropdown` theme is now included in this repo as a custom theme, and we can also edit it in the future if necessary.
