### ISSUE TITLE
Docs are not up-to-date on web page

### ISSUE THREAD

**Issue by marcelklehr** [babe-project/babe-docs#4]
@x-ji how do I update the new docs to the web site?

**Comment by x-ji** [comment]
@marcelklehr  I think the way Github Pages works, the branch `gh-pages` is the branch from which the site is built. We probably merged to the wrong branch and should put the latest updates into the `gh-pages` branch.

**Comment by michael-franke** [comment]
Not sure if I’m missing the point, but if the question was about how to write/update the ‘magpie-docs’ repo for rendering, check out: https://www.mkdocs.org/
[sorry if this was entirely irrelevant]

**Comment by marcelklehr** [comment]
I'm sorry if I wasn't entirely clear. I'm looking for a guide on how to deploy the updated source files of the docs so that the changes are visible on the public web page. Is merging into gh-pages branch enough for this, or do I need to run mkdocs myself locally and push to github pages?

**Comment by x-ji** [comment]
Thanks Michael. What you said is the right way to do so and I just ran `mkdocs gh-deploy` to deploy the latest changes (the git pushing is done automatically). I've also updated the README on this.
