### ISSUE TITLE
Missing example of usage of Record component in built-in screens

### ISSUE THREAD

**Issue by thelogicalgrammar** [babe-project/babe-docs#7]
At the moment, all the occurrences of the Record component in the documentation appear in Slide components in the context of writing custom screens. Therefore, it is not obvious how to use Record with built-in Screens. I figured that Record inside the #stimulus slot works:
```
<CompletionScreen
	// various info
        ...
>
	// Add table to slide
	<template #stimulus>
		<AnswersTable :trialData='trial' />
		<Record :data="trial" />
	</template>
</CompletionScreen>
````
But it doesn't work outside of a named template. 

Perhaps would be good to include this kind of usage in the documentation.

**Comment by marcelklehr** [comment]
Sorry, I forgot about this. The example you posted, works, though, correct?
